name: CC Admin rewards
description: Form to document CC Admin reward shares 
title: "Ada reward for duties performed"
labels: ["CC Admin rewards"]
assignees:
  - Glaxas
body:
  - type: markdown
    attributes:
      value: |
        Enter amount of share points per member and ad extra comments if necessary.
  - type: textarea
    attributes:
      label: CC Admin member share points
      description: |
        examples:
          - **JP (Jonathan Postnikoff)**: 15
          - **Michael Yagi**: 13
          - **Nadim Karam**: 14
      value: |
          - JP (Jonathan Postnikoff):
          - Michael Yagi:
          - Nadim Karam:
          - Nori Nishigaya:
          - Peter Wolcott:
          - Stephan Whitenstall:
      render: markdown
    validations:
      required: false
  - type: textarea
    id: Comment
    attributes:
      label: Extra Comment
      description: Extra comments about reward.
      placeholder: ex. Only allocate X amount of rewards for distribution among all members...
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Agree the information is correct
      description: By submitting this issue, you agree the information provided is correct.
      options:
        - label: I agree the information provided is correct.
          required: true
