blank_issues_enabled: false
contact_links:
  - name: Random Urls if needed
    url: https://github.community/
    about: Go here to.....
  - name: Tasks/Misc
    url: https://docs.google.com/forms/d/e/1FAIpQLSf3HQgwo0q05gmsnBZydDMlGnLW0V7reetmQTJR2Tx5gljQfQ/viewform?usp=sf_link
    about: Google form for tasks/misc ADA requests
