name: Export issues
on:
  workflow_dispatch:
 # schedule:
    # run every 8 hours
  #  - cron:  '0 0,8,16 * * *'
jobs:
  issue:
    runs-on: windows-latest
    name: issueparser
    steps:
    - name: Parse Issue Body
      uses: peter-murray/issue-body-parser-action@v1
      id: issue_body_parser
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
           # This is assuming that you are triggering off the issue, otherwise you will need to know the issue number
          issue_id: ${{ github.event.issue.number }}
          payload_marker: target_payload
  deploy:
    needs: issue
    runs-on: windows-latest
    name: Windows Test Job
    steps:
    - name: Test Custom
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: info
        username: CustomUsername
        color: '#ff00aa'
        avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
        description: This is a custom description.
        details: 'Custom details: Somebody set up us the bomb.'
        footer: This is a footer.
        text: ${{ target_payload }}
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
