name: Export issues
on:
  issues:
    types: [opened, edited, reopened, closed, deleted, labeled, unlabeled]
  #workflow_dispatch:
 # schedule:
    # run every 8 hours
  #  - cron:  '0 0,8,16 * * *'
jobs:
  issue:
    runs-on: ubuntu-latest
    name: discord
    steps:
     - name: Test Custom
       uses: rjstone/discord-webhook-notify@v1
       with:
         severity: info
         username: CustomUsername
         color: '#ff00aa'
         avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
         description: ${{ github.event.issue.number }}
         details: ${{ toJson(github.event.issue.body).line1 }}
         footer: This is a footer.
         text: ${{ github.event.issue.title }}
         webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

 
