on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 12 * * *'
  workflow_dispatch:
env:
  OUTPUT_FILE_NAME: index.html
  COMMITTER_EMAIL: actions@github.com
  COMMITTER_NAME: github-actions
  COMMITTER_USERNAME: github-actions
jobs:
    testing-project:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Project changes past 30 days
              uses: adgcz/project-activity@v1.0.0
              id: project
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  smtp-server: "smtp.gmail.com"
                  smtp-server-port: "587"
                  auth-user: ${{ secrets.EMAIL_USER }}
                  auth-pwd: ${{ secrets.EMAIL_PWD }}
                  email-from: ${{ secrets.EMAIL_FROM }}
                  recipient-emails: ${{ secrets.RECIPIENT_EMAILS }}
                  project-numbers: all
                  days: 30
                  outputPath: ${{ env.OUTPUT_FILE_NAME }}
            - name: Upload summary to artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: kanban
                  path: ${{ env.OUTPUT_FILE_NAME }}
            - name: "Commit if any changes were made"
              run: |
                git remote add github "https://$COMMITTER_USERNAME:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                git pull github ${GITHUB_REF} --ff-only
                if [[ `git status --porcelain` ]]; then
                  git add ${OUTPUT_FILE_NAME}
                  git config --global user.email $COMMITTER_EMAIL
                  git config --global user.name $COMMITTER_NAME
                  git commit -m "Update $OUTPUT_FILE_NAME"
                  git push github HEAD:${GITHUB_REF}
                fi
